# Generated by Django 3.1.7 on 2021-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
